### ISSUE TITLE
Not Premium

### ISSUE THREAD

**Issue by Kr4vKr4v** [VidTuGit/In-Game-Account-Switcher#2]
I have the problemt that if i have my own account, and "Login" it, it counts as an used and not really uses it because im already in that account. Then, i have my alt account, and if i put it in and stuff so its in the list, i cant "Login" it becouse its Not Premium. if i do offline mod i can use it but thats not the point cuz im not a singleplayer player. and if i do that , i cant switch back to my norma l account. Does anyone knows why? Ihave all the passwords an such doublecheckt. maybe it has to do with the **************** at the password menu?

**Comment by VidTuGit** [comment]
1. Did you put email or name into the "Username" field?
2. Do you have an official launcher?
3. What version are you running?
4. Which loader are you using? (Fabric/Forge)
5. Are you using the latest version of the mod? (7.1.0-pre2)

**Comment by Kr4vKr4v** [comment]
1. I tried both, both doesnt work. Email yust stays email on both accounts too
2. Yes, i use the same launcher for both but yes
3. 1.17
4. Fabric
5. Latest for 1.17. The other one crashes my game, even notenoughcrashes cant keep up with that haha.
Q; does it matter with other mods? I got tweakeroo, perspective mod redux, optifine/fabric and a fiew more

**Comment by VidTuGit** [comment]
Other mods should not affect anything.
Generally, you should use email and pass for official accounts and nickname for offline mode.
When I'll get to my PC, I'll look into this issue

**Comment by Kr4vKr4v** [comment]
Thanks, but as i said(i think) if i do email, it yust stays as an email. I also tried going on my alst and then login to my main, but the smae problem stays

**Comment by Kr4vKr4v** [comment]
yeyyyyyy it works! it yust needed to login ;D
